<?php

return '
www.attorneygeneral.gov.uk
www.bonavacantia.gov.uk
www.cps.gov.uk
www.gls.gov.uk
www.hmcpsi.gov.uk
www.attorneygeneral.gov.uk/nfa
www.tsol.gov.uk
www.advantagewm.co.uk
www.acas.org.uk
www.apprenticeships.org.uk
www.biolondon.org.uk
discuss.bis.gov.uk
www.capitalforenterprise.gov.uk
www.cac.gov.uk
www.certoffice.org
www.cflabs.org.uk
www.catribunal.org.uk
www.competition-commission.org.uk
www.consumerfocus.org.uk
www.ipo.gov.uk/ctribunal
www.bis.gov.uk
www.eeda.org.uk
economy.swo.org.uk
www.emda.org.uk
www.englandsrdas.com
www.ecgd.gov.uk
www.fdf.ac.uk
www.ecochecker.co.uk
www.graduateadvantage.co.uk
graduatetalentpool.bis.gov.uk
www.hefce.ac.uk 
www.insolvency.gov.uk
www.inspiredleadership.org.uk
www.investorsinpeople.co.uk
www.ktponline.org.uk
www.learningrecordsservice.org.uk
www.lbro.org.uk
www.london-catalyst.org.uk
www.londondesignmap.org.uk
www.lowpay.gov.uk
www.mas.bis.gov.uk
nationalemployerservice.org.uk
www.nesta.org.uk 
researchtools.lsc.gov.uk/lss
nationaltrainingawards.com
www.nwda.co.uk
nwdabusinessfinance.co.uk
www.ukstandards.org.uk
www.offa.org.uk
www.ome.uk.com
www.onenortheast.co.uk
www.psc.gov.uk
recalledproducts.org
www.regenwm.org
www.rcuk.ac.uk
www.rcuknano.org.uk
www.safelearner.info
www.skillsforjustice-ipds.com
www.seeda.co.uk
www.southeastpartnership.co.uk
www.studentloanrepayment.co.uk
www.slc.co.uk
www.thetakeoverpanel.org.uk
www.innovateuk.org
thedataservice.org.uk
www.diplomainpublicservices.co.uk
www.theia.org.uk
theukrc.org
www.trainingqualitystandard.co.uk
www.ukces.org.uk
www.ukonlinecentres.com
ukrlp.co.uk
www.ukskills.org.uk
www.uk-atomic-energy.org.uk
www.worldskillsuk.org
www.yorkshire-forward.com
www.yorkshirefutures.com
www.charitycommission.gov.uk
www.data4nr.net
www.communities.gov.uk
www.designformanufacture.info
www.fireservicecollege.ac.uk
www.firebuy.gov.uk
www.homesandcommunities.co.uk
www.housing-ombudsman.org.uk
www.info4local.gov.uk
www.iggi.gov.uk
www.lease-advice.org
www.local.communities.gov.uk
www.lgo.org.uk
www.ltgdc.org.uk
www.planningportal.gov.uk
www.rpts.gov.uk
www.standardsforengland.gov.uk
www.tenantservicesauthority.org
www.planning-inspectorate.gov.uk/pins
www.thurrocktgdc.org.uk
www.urbandesigncompendium.co.uk
www.valuationtribunal.gov.uk
www.wndc.co.uk
www.alpha.gov.uk
www.biglotteryfund.org.uk 
www.buyingsolutions.gov.uk
www.cabinetoffice.gov.uk
www.csvacs.gov.uk
www.coi.gov.uk
www.civilservice.gov.uk
www.civilserviceappealboard.gov.uk
www.public-standards.org.uk
www.compactweek.org.uk
www.data.gov.uk
www.direct.gov.uk
faststream.civilservice.gov.uk
www.fundingcentral.org.uk
www.hmg.gov.uk
www.independent.gov.uk
www.innovationlaunchpad.cabinetoffice.gov.uk
www.ogc.gov.uk
www.redtapechallenge.cabinetoffice.gov.uk 
socialenterpriseambassadors.org.uk
carboncalculator.direct.gov.uk
afghanistan.hmg.gov.uk/en
www.thecrownestate.co.uk
activeplaces.com
www.gac.culture.gov.uk
www.artscouncil.org.uk 
www.culturalpropertyadvice.gov.uk
www.culture.gov.uk
www.digitaltelevision.gov.uk
www.flaweb.org.uk
www.gamblingcommission.gov.uk
www.hlf.org.uk
www.hblb.org.uk
www.inspiringlearning.gov.uk
www.mla.gov.uk
www.nationalhistoricships.org.uk
www.natlotcomm.gov.uk
www.olympiclotterydistributor.org.uk
www.peoplesnetwork.gov.uk
www.plr.uk.com
www.sportengland.org
www.ukad.org.uk
www.ukfilmcouncil.org.uk
www.uksport.gov.uk
www.groundstability.com
www.theccc.org.uk
www.decc.gov.uk
www.eca.gov.uk
www.eca.gov.uk/etl
ghgi.decc.gov.uk 
www.nda.gov.uk
www.offshore-sea.org.uk
www.og.decc.gov.uk/pprs/pprsindex
www.agwasteplastics.org.uk
www.ahdb.org.uk
www.balancedseas.org
secure.fera.defra.gov.uk/beebase
www.biomassenergycentre.org.uk/portal/ 
www.cefas.defra.gov.uk
cobody.defra.gov.uk/cobody/cobodyhome.nsf
www.ccwater.org.uk
www.defra.gov.uk
dwi.defra.gov.uk
www.environment-agency.gov.uk
www.fawc.org.uk
www.finding-sanctuary.org 
www.frame.ceh.ac.uk
gla.defra.gov.uk
www.iwac.org.uk
intermet.csl.gov.uk
www.irishseaconservation.org.uk
jncc.defra.gov.uk
www.landshapes.org
www.livingriver.org.uk
magic.defra.gov.uk
intertidalmanagement.co.uk
www.searchmesh.net
www.marinemanagement.org.uk
www.mczmapping.org
naei.defra.gov.uk
ncppb.com
www.nationalforest.org
www.nationalparks.gov.uk
www.nationaltrail.co.uk
www.naturalengland.org.uk
nematodesuk.fera.defra.gov.uk
www.netgainmcz.org
www.netregs.gov.uk
www.recyclenow.com
www.ukbap.org.uk
www.ukcip.org.uk
www.vmd.gov.uk
www.vmd.gov.uk/vpc
www.vmd.gov.uk/vrc
wastedirectory.org.uk
www.wrap.org.uk
childrenact1989regstraining.walkgrove.co.uk
www.education.gov.uk
www.furthermaths.org.uk
governorline.info 
www.ncetm.org.uk
learnerpanel.co.uk
www.togetherfdc.org
www.becta-x.co.uk
www.cafcass.gov.uk
www.childrenscommissioner.gov.uk
www.cwdcouncil.org.uk
diplomavalidator.qcda.gov.uk
www.modernisationonline.org.uk/comptimetable
www.tda.gov.uk/get-into-teaching
www.inca.org.uk
www.modernisationonline.com/compkeydates
mycurriculum.com
www.nationalcollege.org.uk
curriculum.qcda.gov.uk
ncatools.qcda.gov.uk
www.partnershipsforschools.org.uk
www.qcda.gov.uk
www.refernet.org.uk
www.schoolfoodtrust.org.uk
www.tda.gov.uk
www.ypla.gov.uk
cscuk.dfid.gov.uk
www.dfid.gov.uk
www.stabilisationunit.gov.uk
www.aaib.gov.uk
www.dft.gov.uk
www.directlyoperatedrailways.co.uk
www.esdal.com
www.hs2.org.uk
www.highways.gov.uk
www.maib.gov.uk
www.passengerfocus.org.uk
www.raib.gov.uk
www.trafficengland.com
www.trafficradio.org.uk
www.transportdirect.info 
www.arsac.org.uk
www.admlc.org.uk
www.aerc.org.uk
www.appointments.org.uk
www.asthmar-d.org.uk
www.britishmosquitoes.org.uk
www.pharmacopoeia.gov.uk
www.pharmacopoeia.co.uk
www.cqc.org.uk
www.info.doh.gov.uk/Carers/Carersweb.Nsf
www.hpa-quality.org.uk
www.ct-toolkit.ac.uk
www.comeap.org.uk
www.iacoc.org.uk
www.comare.org.uk
www.iacom.org.uk
www.communityhealthpartnerships.co.uk
www.ccpanel.org.uk
www.chre.org.uk
www.dh.gov.uk
www.east-of-england-rdsu.org.uk
www.eric-on-line.co.uk
www.ehic.org.uk/Internet/home.do
www.gscc.org.uk
www.griffininvestigation.org.uk
www.health4work.nhs.uk
www.hpc-uk.org
www.hpa-ne.org.uk
www.hpa-nw.org.uk
www.hpa.org.uk
www.rrsag.org.uk
ehealthlearning.org.uk
www.healthprotectionagency.tv
www.hfea.gov.uk
www.hgc.gov.uk
www.hta.gov.uk
www.imbaprofessional.com
www.irpanel.org.uk
www.invo.org.uk
www.irid.org.uk
www.riskit.org.uk
www.mhra.gov.uk
www.hpa-midas.org.uk
www.monitor-nhsft.gov.uk
www.mthr.org.uk
www.rddirect.org.uk
www.nibsc.ac.uk
www.hpa-standardmethods.org.uk
www.nhsidentity.nhs.uk
www.photolibrary.nhs.uk
www.nhsplus.nhs.uk
www.hpa-radiationservices.org.uk
www.sacn.gov.uk
shape.dh.gov.uk
www.socialcarecareers.co.uk/socialcare/ 
www.socialworkcareers.co.uk/socialwork/ 
www.britishticks.org.uk
www.ukradon.org
www.childmaintenance.org
www.cmoptions.org
www.csa.gov.uk
www.dwp.gov.uk
www.gateway.gov.uk 
www.hse.gov.uk
www.ind-case-exam.org.uk
www.ppfo.org.uk
www.pensions-ombudsman.org.uk
www.pesticides.gov.uk
www.thepensionsregulator.gov.uk
www.trusteetoolkit.com
www.britishcouncil.org
www.fcoservices.gov.uk
www.fco.gov.uk
www.careersinbritishintelligence.co.uk
www.gogapyear.com
www.govcertuk.gov.uk
www.gchq.gov.uk
www.gchq-careers.co.uk
www.gbcc.org.uk
www.marshallscholarship.org
www.cesg.gov.uk
www.counter-eavesdropping.gov.uk
www.wfd.org
www.wiltonpark.org.uk
www.forestry.gov.uk
www.forestresearch.gov.uk
www.food.gov.uk
www.gad.gov.uk
www.equalityhumanrights.com
www.thewnc.org.uk
www.adjudicatorsoffice.gov.uk
www.businesslink.gov.uk
www.hmrc.gov.uk
www.uktradeinfo.com 
thegfp.treasury.gov.uk
www.hm-treasury.gov.uk
www.redbox.gov.uk
www.ukfi.gov.uk
www.actionfraud.org.uk
www.bia.homeoffice.gov.uk
www.cpni.gov.uk
cfnp.npia.police.uk
www.forensic.gov.uk
www.equalities.gov.uk
www.hmic.gov.uk
www.homeoffice.gov.uk
www.ipcc.gov.uk
isa.homeoffice.gov.uk
www.ipt-uk.com
www.lifeintheuktest.gov.uk
www.secureyourfertiliser.gov.uk
www.npia.police.uk/en/home.htm
www.oisc.gov.uk
policerecruitment.homeoffice.gov.uk
www.soca.gov.uk
www.sia.homeoffice.gov.uk
www.thinkuknow.co.uk
www.ukvisas.gov.uk
www.warp.gov.uk
www.armedforcesday.org.uk
www.science.mod.uk
www.dasa.mod.uk
www.blogs.mod.uk
defenceconsultations.org.uk
www.defenceimagedatabase.mod.uk/fotoweb
www.defencenewsimagery.mod.uk
www.dstl.gov.uk
www.dsg.mod.uk
www.edisposals.com
www.dnotice.org.uk
easytide.ukho.gov.uk/EasyTide
www.futureofnavigation.com
websurf.hmnao.com
www.metoffice.gov.uk
www.mod.uk
www.contracts.mod.uk
www.sabre.mod.uk
www.dstan.mod.uk
www.ukho.gov.uk
www.veterans-uk.info
virtual.nationalschool.gov.uk/AJC
www.appsi.gov.uk 
www.ccrc.gov.uk
www.edinburgh-gazette.co.uk 
www.ico.gov.uk
www.jcpc.gov.uk
www.landregistry.gov.uk
www.legalombudsman.org.uk
www.legalservicesboard.org.uk
www.legalservices.gov.uk
training.legalservices.gov.uk
www.legalservicesconsumerpanel.org.uk
www.justice.gov.uk
www.moneyclaim.gov.uk
www.nationalarchives.gov.uk
www.official-documents.gov.uk
www.legislation.gov.uk 
www.possessionclaim.gov.uk/pcol
www.ppo.gov.uk 
www.adr.civiljusticecouncil.gov.uk
www.nio.gov.uk
www.nationalschool.gov.uk
www.nsandi.com
www.oag.gov.uk
www.ofgem.gov.uk
www.theeab.org.uk
www.ofqual.gov.uk
www.ofsted.gov.uk
www2.crw.gov.uk/pr
www.oft.gov.uk
www.ofwat.gov.uk
www.commonsleader.gov.uk
www.rail-reg.gov.uk
www.ajtc.gov.uk
www.sis.gov.uk
www.fsa.gov.uk
www.mi5.gov.uk
www.mi6officers.co.uk
www.moneyadviceservice.org.uk
www.moneymadeclear.fsa.gov.uk
www.sd-commission.org.uk
www.royal.gov.uk
www.princeofwales.gov.uk
www.number10.gov.uk
www.dmo.gov.uk
www.royalmint.com
www.sfo.gov.uk
www.scotlandoffice.gov.uk
www.census.gov.uk
censusjobs.co.uk
neighbourhood.statistics.gov.uk
www.nomisweb.co.uk
www.ons.gov.uk
www.statistics.gov.uk
www.statistics.gov.uk/hub
www.statisticsauthority.gov.uk
www.businessinasia.co.uk
www.creative-industries.co.uk
www.londonpressservice.org.uk
www.technologyworld.uk.com
www.ukadvancedengineering.com
www.ukan.ukti.gov.uk
www.ukenergyexcellence.com
www.identity.uktradeinvest.gov.uk
www.ukti.gov.uk
www.uktisoutheast.com
www.walesoffice.gov.uk
';

?>
